#!/usr/bin/python

"""
[fTerm] f-i

This program is the main file for fTerm.
"""

# NOTE: this is extraneous
# pylint: disable-msg=C0103

# NOTE: this would make line 19 unreadable
# pylint: disable-msg=C0301

# allows parsing of arguments
from sys import argv

# parser
import parser

# import actual functions
from load import verbs

def shellquote(s):
    """Fix quotes for terminal."""
    return "'" + s.replace("'", "'\\''") + "'"

def run():
    """The main function for fTerm"""
    argnum = len(argv)
    if argnum == 1:
        print "echo '[f-i] Please specify a command (e.g., f swap file1 file2)';"
        return
    else:
        # retrieve the function
        try:
            suggestion = "[f-i] "
            f = parser.parse(argv[1])
            suggestion += f
            f = verbs[f]
        except IndexError:
            print "echo '[f-i] Invalid function %s';" % (argv[1]),
            return

        # ensure that the correct number of arguments are being passed
        if argnum - 2 != f.func_code.co_argcount:
            print "echo '[f-i] Wrong number of arguments for function %s';" % (argv[1])
        else:
            # args = map(shellquote, argv[2:])
            #args = [parser.nounParse(x) for x in argv[2:]]
            args = argv[2:]
            suggestion += " " + " ".join(args)
            print "read -p \'%s\' -n 1 -r; if [[ $REPLY =~ ^$ ]]; then %s fi" % (suggestion, f(*args))
            # print f(*args),

run()
